administracion/urls.py
from . import views
from django.urls import path

app_name = 'administracion'
urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name='detalle'),
]

inventario/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('relacion/', include('relacion.urls')),
    path('administracion/', include('administracion.urls')),
]

relacion/urls.py
from django.urls import path



from . import views

app_name = 'relacion'
urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name='detalle'),
    path('<int:pk>/buscar/',views.BuscarView.as_view(), name='buscar'),
    path('<int:pk>/entrada/',views.EntradaView.as_view(), name='entrada'),
    path('<int:pk>/salida/',views.SalidaView.as_view(), name='salida'),
    path('<int:pk>/borrar/',views.BorrarView.as_view(), name='borrar'),
    path('catalogo/',views.CatalogoView.as_view(), name='catalogo'),
    #path('catalogo/nuevo',views.BorrarView.as_view('nuevo'),
]
    

administracion/models.py
from django.db import models

# Create your models here.

class Bodegas(models.Model):
    nombre = models.CharField(max_length=25)
    calle = models.CharField(max_length=30)
    exterior = models.CharField(max_length=10)
    interior = models.CharField(max_length=15)
    fraccionamiento = models.CharField(max_length=30)
    ciudad = models.CharField(max_length=30)
    codigo_postal = models.CharField(max_length=6)
    entidad = models.CharField(max_length=25)
    pais = models.CharField(max_length=25)
    telefono = models.CharField(max_length=20)
    class Meta:
        verbose_name_plural = "Bodegas"
    def __str__(self):
        return(self.nombre)

relacion/models.py
from django.db import models
from django.utils import timezone
import datetime

from administracion.models import Bodegas

# Create your models here.

class Item(models.Model):
    nombre = models.CharField(max_length=50)
    sku = models.CharField(max_length=12)
    descripcion = models.CharField(max_length=100)
    costo = models.FloatField()
    peso = models.FloatField()
    ancho = models.FloatField()
    alto = models.FloatField()
    profundidad = models.FloatField()
    def __str__(self):
        return(self.nombre)
    
class EnSal(models.Model):
    mov = models.CharField(max_length=10)
    def __str__(self):
        return(self.mov)

class Movimiento(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    bodega = models.ForeignKey(Bodegas, on_delete=models.CASCADE)
    fecha = models.DateTimeField('Fecha de Movimiento')
    movimiento = models.ForeignKey(EnSal, on_delete=models.CASCADE) #Should not be cascade, check later
    def __str__(self):
        return str(self.movimiento)+" de "+str(self.item)

administracion/views.py
from django.shortcuts import render
from django.views import generic
from . import models

# Create your views here.

class IndexView(generic.ListView):
    model = models.Bodegas
    context_object_name = 'lasbodegas'
    template_name = 'administracion/index.html'


class DetailView(generic.DetailView):
    model = models.Bodegas
    context_object_name = 'bodega'
    template_name = 'administracion/detalle.html'

relacion/views.py
from django.shortcuts import render
from django.views import generic
from . import models

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = "relacion/index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        litems = models.Item.objects.all()
        lstock = models.Movimiento.objects.all()
        cant = {}
        i = 0
        print(litems)
        print(lstock)
        for lit in litems:
            for stk in lstock:
                if lit.id == stk.item.id:
                    if str(stk.movimiento) == "entrada":
                        i+=stk.cantidad
                    if str(stk.movimiento) == "salida":
                        i-=stk.cantidad
                    print(i)
                    cant[lit.nombre] = i
        context['lista_de_items'] = models.Item.objects.all()[:5]
        context['stock'] = models.Movimiento.objects.all()[:5]
        context['cantidades'] = cant
        return context    

class oldIndexView(generic.ListView):
    model = models.Item
    context_object_name = 'lista_de_items'
    template_name = "relacion/index.html"

class DetailView(generic.DetailView):
    model = models.Item
    context_object_name = 'item'
    template_name = "relacion/detalle.html"

class BuscarView(generic.ListView):
    model = models.Item
    context_object_name = 'buscar'
    template_name = "relacion/buscar.html"

class EntradaView(generic.ListView):
    model = models.Item
    context_object_name = 'entrada'
    template_name = "relacion/entrada.html"

class SalidaView(generic.ListView):
    model = models.Item
    context_object_name = 'salida'
    template_name = "relacion/salida.html"

class CatalogoView(generic.ListView):
    model = models.Item
    context_object_name = 'catalogo'
    template_name = "relacion/catalogo.html"

class BorrarView(generic.DeleteView):
    model = models.Item
    context_object_name = 'borrar'
    template_name = "relacion/borrar.html"

administracion/templates/administracion/detalle.html
<html>
<body>
{% if bodega %}
<h2>BODEGA: {{ bodega.nombre }} </h2>
<ul>
<li>{{ bodega.calle }} - {{ bodega.exterior }} int {{ bodega.interior }}</li>
<li>{{ bodega.fraccionamiento }}</li>
<li>{{ bodega.ciudad }} CP (Zip Code) {{ bodega.codigo_postal }}</li>
<li>{{ bodega.entidad }}</li>
<li>{{ bodega.pais }}</li>
<li>Teléfono: {{ bodega.telefono }}</li>
</ul>

<h4><a href="https://www.google.com/maps/search/{{ bodega.calle|urlencode }}+{{ bodega.exterior|urlencode }}+{{ bodega.fraccionamiento|urlencode }}+{{ bodega.ciudad|urlencode }}+{{ bodega.entidad|urlencode }}+{{ bodega.pais|urlencode }}" target="_new">Buscar ubicación</a></h4>
{% else %}
<h3 color="red">No hay detalles de la bodega</h3>
{% endif %}
</body>
</html>

administracion/templates/administracion/index.html
<html>
<body>
{% if lasbodegas %}
<h3>Bodegas:<h3>
<ul>
{% for bodega in lasbodegas %}
    <li><a href="{% url 'administracion:detalle' bodega.id %}">{{ bodega.nombre }} {{ bodega.id }}</a></li>
{% endfor %}
</ul>
{% else %}
<h3 color="red">No hay bodegas en el sistema</h3>
{% endif %}
</body>
</html>

relacion/templates/relacion/detalle.html
<html>
<body>
{% if item %}
<h2>{{ item.nombre }} </h2>
<ul>
<li>SKU: {{ item.sku }} - Costo: ${{ item.costo }}</li>
<li>{{ item.descripcion }}</li>
<li>Peso: {{ item.peso }}g</li>
<li>Ancho: {{ item.ancho }}cm</li>
<li>Alto: {{ item.alto }}</li>
<li>Profundidad: {{ item.profundidad }}</li>
</ul>

{% else %}
<h3 color="red">No hay detalles del item</h3>
{% endif %}
</body>
</html>

relacion/templates/relacion/index.html
<html>
<body>
{% if lista_de_items %}
<h2>Items:</h2>
<br>
<h3>Catálogo:</h3>
<ul>
{% for item in lista_de_items %}
    <li><a href="{% url 'relacion:detalle' item.id %}">{{ item.sku }}</a> - {{ item.nombre }} $ {{item.costo}}</li>
{% endfor %}
</ul>
<h3>Stock:</h3>
<p>
{{ cantidades }}
</p>
{% else %}
<h3 color="red">No hay items en el sistema</h3>
{% endif %}
</body>
</html>